# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BkAT3 < Formula
  desc "Work with Buildkite from the command-line"
  homepage "https://github.com/buildkite/cli"
  version "3.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/buildkite/cli/releases/download/v3.1.0/bk_3.1.0_macOS_amd64.zip"
      sha256 "edc4b8f10fb20ad286c657bacc4cef48080ba2b98bb229da7df59b753bd8795c"

      def install
        bin.install "bk"
      end
    end
    on_arm do
      url "https://github.com/buildkite/cli/releases/download/v3.1.0/bk_3.1.0_macOS_arm64.zip"
      sha256 "8b991fb25c10e22ffe552a1ee27d83e9aa46af0b236dafc44797c1d821ff05a1"

      def install
        bin.install "bk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buildkite/cli/releases/download/v3.1.0/bk_3.1.0_linux_amd64.tar.gz"
        sha256 "0383372bde702e2c1cf61b68e4d03215bc22cb9c1b3a2d24c9a91180950823cd"

        def install
          bin.install "bk"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/buildkite/cli/releases/download/v3.1.0/bk_3.1.0_linux_armv6.tar.gz"
        sha256 "65ad1134821ca9111f84028b57e22f127d182ec2cafc5e5a93b9ba107bd9fb8a"

        def install
          bin.install "bk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buildkite/cli/releases/download/v3.1.0/bk_3.1.0_linux_arm64.tar.gz"
        sha256 "8587e22112324508fd01f407e6e2c700d6bb77703f6c14c4b5a6cc4d0068ae66"

        def install
          bin.install "bk"
        end
      end
    end
  end

  def caveats
    <<~EOS
      This is beta software

      For any questions, issues or feedback, please file an issue at https://github.com/buildkite/cli/issues
    EOS
  end

  test do
    system "#{bin}/bk version"
  end
end
