# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BkAT3 < Formula
  desc "Work with Buildkite from the command-line"
  homepage "https://github.com/buildkite/cli"
  version "3.0.0-beta.20240705"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/buildkite/cli/releases/download/v3.0.0-beta.20240705/bk_3.0.0-beta.20240705_macOS_amd64.zip"
      sha256 "7beff4229dfd556b2b6383a35992adcc1d7c1872fcf02c8a2ee6ab0b912aace6"

      def install
        bin.install "bk"
      end
    end
    on_arm do
      url "https://github.com/buildkite/cli/releases/download/v3.0.0-beta.20240705/bk_3.0.0-beta.20240705_macOS_arm64.zip"
      sha256 "1eda7eaf7fe6c904e40ab082eb1ac9fd249d3747862325016fa37397bf94d4a7"

      def install
        bin.install "bk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buildkite/cli/releases/download/v3.0.0-beta.20240705/bk_3.0.0-beta.20240705_linux_amd64.tar.gz"
        sha256 "6e183db576bf6c1a0bbe05b2cc28684487e8e37ea50f12f73b87a18aa26ce097"

        def install
          bin.install "bk"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/buildkite/cli/releases/download/v3.0.0-beta.20240705/bk_3.0.0-beta.20240705_linux_armv6.tar.gz"
        sha256 "49e73ac3bb0ee2068d63a0499af8f2d2f8fb8b7da3fe03b65fe565ad8db3d9a2"

        def install
          bin.install "bk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buildkite/cli/releases/download/v3.0.0-beta.20240705/bk_3.0.0-beta.20240705_linux_arm64.tar.gz"
        sha256 "f391e02594c73696f5d26e41b1d95aee55ab515706605b41ba823e1e0c37226c"

        def install
          bin.install "bk"
        end
      end
    end
  end

  def caveats
    <<~EOS
      This is beta software

      For any questions, issues or feedback, please file an issue at https://github.com/buildkite/cli/issues
    EOS
  end

  test do
    system "#{bin}/bk version"
  end
end
