# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bktec < Formula
  desc "Buildkite Test Engine Client"
  homepage "https://github.com/buildkite/test-engine-client"
  version "1.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/buildkite/test-engine-client/releases/download/v1.6.1/bktec_1.6.1_darwin_amd64"
      sha256 "5d402a48825b33ce7a63798fd4b0714b2a1ba1ebfc5ddcca4260f6a349ee3131"

      def install
        bin.install "bktec_1.6.1_darwin_amd64" => "bktec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/buildkite/test-engine-client/releases/download/v1.6.1/bktec_1.6.1_darwin_arm64"
      sha256 "32f2eaee6b5b7bb73f98a2523db5df0f412ca941f0738bf1e515342f83e9a0d0"

      def install
        bin.install "bktec_1.6.1_darwin_arm64" => "bktec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buildkite/test-engine-client/releases/download/v1.6.1/bktec_1.6.1_linux_amd64"
        sha256 "2dffd4124cab2ebdd348f5fe9d342dcf918549b0337e9ccb5294c8d007d4b788"

        def install
          bin.install "bktec_1.6.1_linux_amd64" => "bktec"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buildkite/test-engine-client/releases/download/v1.6.1/bktec_1.6.1_linux_arm64"
        sha256 "91ee924a8d64d6a22c1616aa18f6f3d7376526cbc71a612e957666cd7b43a26a"

        def install
          bin.install "bktec_1.6.1_linux_arm64" => "bktec"
        end
      end
    end
  end

  test do
    version_output = shell_output("bktec --version")
    assert_match "v#{version}\n", version_output
  end
end
