# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestSplitter < Formula
  desc "Buildkite test splitting client"
  homepage "https://github.com/buildkite/test-splitter"
  version "0.8.1"

  on_macos do
    on_intel do
      url "https://github.com/buildkite/test-splitter/releases/download/v0.8.1/test-splitter_0.8.1_darwin_amd64"
      sha256 "c21d7a24a5c0b89f727f8bdc542346df1f14caacfc458384b3a101ba9a46106b"

      def install
        bin.install "test-splitter_0.8.1_darwin_amd64" => "test-splitter"
      end
    end
    on_arm do
      url "https://github.com/buildkite/test-splitter/releases/download/v0.8.1/test-splitter_0.8.1_darwin_arm64"
      sha256 "fe174bbfae7abe8d2fe3de4b2ce2b7f065bed894068a1c1a7d01346bbce85fcb"

      def install
        bin.install "test-splitter_0.8.1_darwin_arm64" => "test-splitter"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buildkite/test-splitter/releases/download/v0.8.1/test-splitter_0.8.1_linux_amd64"
        sha256 "0828ad2c1f6929dce0c3ad0574fa2eb5bdc71db6d11d3f4fcb277bb60c4ffd1a"

        def install
          bin.install "test-splitter_0.8.1_linux_amd64" => "test-splitter"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buildkite/test-splitter/releases/download/v0.8.1/test-splitter_0.8.1_linux_arm64"
        sha256 "cca42dae6c2bd66a06ef29faa3ab03b22e7979de56f1289d7b49b4d851e27093"

        def install
          bin.install "test-splitter_0.8.1_linux_arm64" => "test-splitter"
        end
      end
    end
  end

  test do
    version_output = shell_output("test-splitter --version")
    assert_match "v#{version}\n", version_output
  end
end
