# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestSplitter < Formula
  desc "Buildkite test splitting client"
  homepage "https://github.com/buildkite/test-splitter"
  version "0.9.0"

  on_macos do
    on_intel do
      url "https://github.com/buildkite/test-splitter/releases/download/v0.9.0/test-splitter_0.9.0_darwin_amd64"
      sha256 "4c615a5f87bdc1cfab73054223f85ba8ad7a58152e9413ef1d1a2649e69a48ca"

      def install
        bin.install "test-splitter_0.9.0_darwin_amd64" => "test-splitter"
      end
    end
    on_arm do
      url "https://github.com/buildkite/test-splitter/releases/download/v0.9.0/test-splitter_0.9.0_darwin_arm64"
      sha256 "45a21b51974967f78a88b47b289e9f1b9b8a46835ed5c491a002982d002fa1c5"

      def install
        bin.install "test-splitter_0.9.0_darwin_arm64" => "test-splitter"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buildkite/test-splitter/releases/download/v0.9.0/test-splitter_0.9.0_linux_amd64"
        sha256 "d0c293feca59be9302fcf6e9d0e56783644094cb22395afff09cb0258ed055b1"

        def install
          bin.install "test-splitter_0.9.0_linux_amd64" => "test-splitter"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buildkite/test-splitter/releases/download/v0.9.0/test-splitter_0.9.0_linux_arm64"
        sha256 "21793c981ddd789cac3d6dba1eb38fe31c7d2895a07dbd02cf7e025ce7879d7f"

        def install
          bin.install "test-splitter_0.9.0_linux_arm64" => "test-splitter"
        end
      end
    end
  end

  test do
    version_output = shell_output("test-splitter --version")
    assert_match "v#{version}\n", version_output
  end
end
