# This file was generated by GoReleaser. DO NOT EDIT.
cask "buildkite-mcp-server" do
  desc "Model Context Protocol server for Buildkite"
  homepage "https://github.com/buildkite/buildkite-mcp-server"
  version "0.7.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "buildkite-mcp-server"

  on_macos do
    on_intel do
      url "https://github.com/buildkite/buildkite-mcp-server/releases/download/v0.7.2/buildkite-mcp-server_Darwin_x86_64.tar.gz"
      sha256 "a78389705265527945a277dee00ec8ae3bfd1d3309db261dc1b1a7aa2dc3c68a"
    end
    on_arm do
      url "https://github.com/buildkite/buildkite-mcp-server/releases/download/v0.7.2/buildkite-mcp-server_Darwin_arm64.tar.gz"
      sha256 "e6c06051a51aa1eb93fbe6c3d6af23b6ddce867ab6bba264bdd2b7c41fa9a0f8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/buildkite/buildkite-mcp-server/releases/download/v0.7.2/buildkite-mcp-server_Linux_x86_64.tar.gz"
      sha256 "4b3c72b87478fbbb6c95e18e78312ea1f8dc5f33f924e96c3a13d2b2eb8d925c"
    end
    on_arm do
      url "https://github.com/buildkite/buildkite-mcp-server/releases/download/v0.7.2/buildkite-mcp-server_Linux_arm64.tar.gz"
      sha256 "f027b69cf156a222fc8eb16249fa472001fb8504c0329a1663c9d83321b51f32"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/buildkite-mcp-server"]
    end
  end

  # No zap stanza required
end
