# This file was generated by GoReleaser. DO NOT EDIT.
cask "buildkite-mcp-server" do
  desc "Model Context Protocol server for Buildkite"
  homepage "https://github.com/buildkite/buildkite-mcp-server"
  version "0.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "buildkite-mcp-server"

  on_macos do
    on_intel do
      url "https://github.com/buildkite/buildkite-mcp-server/releases/download/v0.9.0/buildkite-mcp-server_Darwin_x86_64.tar.gz"
      sha256 "e49315dd5b918ee7b8bfef0a46946e616551dc80c63a6041d72cc5caa0feec22"
    end
    on_arm do
      url "https://github.com/buildkite/buildkite-mcp-server/releases/download/v0.9.0/buildkite-mcp-server_Darwin_arm64.tar.gz"
      sha256 "60e05025440a193d049e60b12185aae28da44ecc57e646edfbb7cbc9639c322a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/buildkite/buildkite-mcp-server/releases/download/v0.9.0/buildkite-mcp-server_Linux_x86_64.tar.gz"
      sha256 "7749c15d32ca159234d56307ae1688101a12ca63fea73feee23c55218a478f88"
    end
    on_arm do
      url "https://github.com/buildkite/buildkite-mcp-server/releases/download/v0.9.0/buildkite-mcp-server_Linux_arm64.tar.gz"
      sha256 "63087c50c62dfce03e2a84af0bfae440d2d070d55f44577c86d6037ce01ae4c7"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/buildkite-mcp-server"]
    end
  end

  # No zap stanza required
end
