# This file was generated by GoReleaser. DO NOT EDIT.
cask "buildkite-mcp-server" do
  desc "Model Context Protocol server for Buildkite"
  homepage "https://github.com/buildkite/buildkite-mcp-server"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "buildkite-mcp-server"

  on_macos do
    on_intel do
      url "https://github.com/buildkite/buildkite-mcp-server/releases/download/v0.6.0/buildkite-mcp-server_Darwin_x86_64.tar.gz"
      sha256 "f629b7587ed2511651e0d3b5680e22d0dca1e2be66ac54014a1b85063da4a4a5"
    end
    on_arm do
      url "https://github.com/buildkite/buildkite-mcp-server/releases/download/v0.6.0/buildkite-mcp-server_Darwin_arm64.tar.gz"
      sha256 "5fd267027b3c1e5dab343c6fda43b9f1aac7015b92090dd1b9a46746110d4413"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/buildkite/buildkite-mcp-server/releases/download/v0.6.0/buildkite-mcp-server_Linux_x86_64.tar.gz"
      sha256 "70223f5cb5be829f72a742c360e6a320397b37e3e443005148f16efb763ed51f"
    end
    on_arm do
      url "https://github.com/buildkite/buildkite-mcp-server/releases/download/v0.6.0/buildkite-mcp-server_Linux_arm64.tar.gz"
      sha256 "58e73d54948bdc927e24d5bb939827f84453fd79275a6b97accebc257cda208f"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/buildkite-mcp-server"]
    end
  end

  # No zap stanza required
end
