# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BkAT3 < Formula
  desc "Work with Buildkite from the command-line"
  homepage "https://github.com/buildkite/cli"
  version "3.28.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/buildkite/cli/releases/download/v3.28.1/bk_3.28.1_macOS_amd64.zip"
      sha256 "3adb2c7e7185c477a0ca7f1a7f37d79675831c1eae392ec6241167585a0fe361"

      def install
        bin.install "bk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/buildkite/cli/releases/download/v3.28.1/bk_3.28.1_macOS_arm64.zip"
      sha256 "7ceceeff19bb17048593b4d19b02bc5c6bf52f6096924aac67918bf519ae46f0"

      def install
        bin.install "bk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/buildkite/cli/releases/download/v3.28.1/bk_3.28.1_linux_amd64.tar.gz"
      sha256 "9a1d44c5ae3dbc00b9ff13cb13f33937964d778775601c87de3ac3540e5bd765"
      def install
        bin.install "bk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/buildkite/cli/releases/download/v3.28.1/bk_3.28.1_linux_arm64.tar.gz"
      sha256 "680a7bc0b8727ac3836667bc74549cfd8b6be09952eb9b042524d5168c76151c"
      def install
        bin.install "bk"
      end
    end
  end

  test do
    system "#{bin}/bk version"
  end
end
