# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BkAT3 < Formula
  desc "Work with Buildkite from the command-line"
  homepage "https://github.com/buildkite/cli"
  version "3.34.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/buildkite/cli/releases/download/v3.34.0/bk_3.34.0_macOS_amd64.zip"
      sha256 "e6946d0bc396a1655576b707b822def215531e8237de6090e0ba3f8c176bc94d"

      define_method(:install) do
        bin.install "bk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/buildkite/cli/releases/download/v3.34.0/bk_3.34.0_macOS_arm64.zip"
      sha256 "5c4c7ac07241322c7b66faf3e65dd807eec8b814db3a47af813ccaaf10f0c632"

      define_method(:install) do
        bin.install "bk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/buildkite/cli/releases/download/v3.34.0/bk_3.34.0_linux_amd64.tar.gz"
      sha256 "029ad322edafa50bd7a7ca7b0cc0aa3b4032814c11e06eafd5ca6d88fb89c9f5"
      define_method(:install) do
        bin.install "bk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/buildkite/cli/releases/download/v3.34.0/bk_3.34.0_linux_arm64.tar.gz"
      sha256 "5f8135bbaaeeaa51ebebb50113f210871c051ef6b9c31c8f079b155a82c8b133"
      define_method(:install) do
        bin.install "bk"
      end
    end
  end

  test do
    system "#{bin}/bk version"
  end
end
