# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bktec < Formula
  desc "Buildkite Test Engine Client"
  homepage "https://github.com/buildkite/test-engine-client"
  version "2.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/buildkite/test-engine-client/releases/download/v2.5.0/bktec_2.5.0_darwin_amd64"
      sha256 "8761fca71b0aa2dfede73207576cefe273b876648ab6f696511fba7d16f978da"

      define_method(:install) do
        bin.install "bktec_2.5.0_darwin_amd64" => "bktec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/buildkite/test-engine-client/releases/download/v2.5.0/bktec_2.5.0_darwin_arm64"
      sha256 "66f3da82371b0c813ba79eba6fa4247bf42959dc009787dd514f906b5c4aef7d"

      define_method(:install) do
        bin.install "bktec_2.5.0_darwin_arm64" => "bktec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/buildkite/test-engine-client/releases/download/v2.5.0/bktec_2.5.0_linux_amd64"
      sha256 "3887013300c4241220c5f0869cc573635e2e2d293a008b574e670c1dc4a26e89"
      define_method(:install) do
        bin.install "bktec_2.5.0_linux_amd64" => "bktec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/buildkite/test-engine-client/releases/download/v2.5.0/bktec_2.5.0_linux_arm64"
      sha256 "c3da86501f2f377182290632b627730c1067ae853148e1ac68452f937b6d1965"
      define_method(:install) do
        bin.install "bktec_2.5.0_linux_arm64" => "bktec"
      end
    end
  end

  test do
    version_output = shell_output("bktec --version")
    assert_match "v#{version}\n", version_output
  end
end
